#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 31 11:32:45 2018

@author: elenachumakova
"""

# Calculate factorial using recursion:
def fact(n):
    if n == 1:
        return 1
    else:
        return n*fact(n-1)
    
#find factorial of 4
print(fact(4))
