#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 24 14:56:20 2018

@author: elenachumakova
"""

#Guess the square root of a given number using Newton Raphson law
#track how close am I to the answer:
epsilon = 0.01
#given number:
y = 24.0
#initial guess:
guess = y/2.0
numGuesses = 0 

while abs(guess*guess - y) >= epsilon:
    numGuesses += 1
    guess = guess - (((guess**2) - y)/(2*guess))
print('numGuesses = ' + str(numGuesses))
print('Square root of ' + str(y) + ' is about ' + str(guess))
