#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 31 12:15:03 2018

@author: elenachumakova
"""

# Towers of Hanoi
"""
On the Teple of Hanoi there are 3 tall spikes.
Each spike has 64 different sized discs in descreasing order
(smallest disk is at the top).
We need to move stack to second spike one disk at a time
so that a larger disc never covers up a small disk.
"""
def printMove(fr, to):
    print('move from ' + str(fr) + ' to ' + str(to))
    
def Towers(n, fr, to, spare):
    if n == 1:
        printMove(fr, to)
    else:
        Towers(n-1, fr, spare, to)
        Towers(1, fr, to, spare)
        Towers(n-1, spare, to, fr)
